monitor.info:
    path: /info
    methods: [GET]
    defaults:
        _controller: openconext.monitor.controller.info

monitor.health:
    path: /health
    methods: [GET]
    defaults:
        _controller: openconext.monitor.controller.health